name: Test
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build
    
    - name: Test
      run: make test

    - name: upload simd binary
      uses: actions/upload-artifact@v1
      with:
        name: simd
        path: ./build

  e2e:
    name: e2e-test
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: download simd
      uses: actions/download-artifact@v1
      with:
        name: simd
        path: ./build

    - name: chmod
      run: chmod +x ./build/*

    - name: build a test network
      run: make -C tests test-network

    - name: e2e-test
      run: make -C tests e2e-test
